require('dotenv').config();
const bcrypt = require('bcryptjs');
const { PrismaClient } = require('@prisma/client');
const { PrismaPg } = require('@prisma/adapter-pg');

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const today = new Date();
const isoDaysFromNow = (days) => {
  const d = new Date(today);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
};

async function main() {
  const password = await bcrypt.hash('tms@1234', 10);

  // --- Users (emails must match the Quick Login buttons in frontend/app/login/page.tsx) ---
  const users = [
    { id: 'U001', name: 'Abebe Kebede', email: 'admin@tms.in', role: 'Super Admin', status: 'Active', permissions: ['all'] },
    { id: 'U002', name: 'Priya Sharma', email: 'priya@tms.in', role: 'Fleet Manager', status: 'Active', permissions: ['fleet', 'drivers', 'trips', 'maintenance'] },
    { id: 'U003', name: 'Karan Mehta', email: 'karan@tms.in', role: 'Dispatcher', status: 'Active', permissions: ['trips', 'fleet'] },
    { id: 'U004', name: 'Nisha Patel', email: 'nisha@tms.in', role: 'Accountant', status: 'Active', permissions: ['costing', 'accounts', 'petty-cash'] },
    { id: 'U005', name: 'Tigist Alemu', email: 'viewer@tms.in', role: 'Viewer', status: 'Active', permissions: ['view'] },
    { id: 'U006', name: 'Dawit Tesfaye', email: 'dawit@tms.in', role: 'Fleet Manager', status: 'Inactive', permissions: ['fleet', 'drivers'] },
  ];
  for (const u of users) {
    await prisma.user.upsert({ where: { id: u.id }, update: {}, create: { ...u, password, lastLogin: null } });
  }

  // --- Vehicles (Ethiopia-style plates, common East African fleet trucks) ---
  const vehicles = [
    { id: 'V001', regNumber: 'ET-AA-23715', make: 'Isuzu', model: 'FRR 90 (10T)', year: 2021, category: 'Medium Truck', ownershipType: 'Owned', capacity: '10 Ton', fuelType: 'Diesel', status: 'Running', driverId: 'D001', odometer: 184230, location: { lat: 9.0192, lng: 38.7468, city: 'Addis Ababa' }, speed: 62, lastService: isoDaysFromNow(-25), insurance: isoDaysFromNow(140), fitness: isoDaysFromNow(95), permit: isoDaysFromNow(210), utilization: 82, purchasedAgency: 'Moenco PLC', vehicleValue: 4200000, emiEnabled: 'Yes', monthlyEMI: 65000, loanBank: 'Commercial Bank of Ethiopia' },
    { id: 'V002', regNumber: 'ET-AA-44589', make: 'Sinotruk', model: 'Howo (25T)', year: 2020, category: 'Heavy Truck', ownershipType: 'Owned', capacity: '25 Ton', fuelType: 'Diesel', status: 'Idle', driverId: 'D002', odometer: 256410, location: { lat: 9.0192, lng: 38.7468, city: 'Addis Ababa' }, speed: 0, lastService: isoDaysFromNow(-12), insurance: isoDaysFromNow(20), fitness: isoDaysFromNow(310), permit: isoDaysFromNow(180), utilization: 64, purchasedAgency: 'Sino Trucks Ethiopia', vehicleValue: 5800000, emiEnabled: 'No', monthlyEMI: 0, loanBank: 'N/A' },
    { id: 'V003', regNumber: 'ET-OR-11296', make: 'FAW', model: 'J6 (15T)', year: 2022, category: 'Medium Truck', ownershipType: 'Leased', capacity: '15 Ton', fuelType: 'Diesel', status: 'Running', driverId: 'D003', odometer: 98200, location: { lat: 8.5400, lng: 39.2700, city: 'Adama' }, speed: 71, lastService: isoDaysFromNow(-5), insurance: isoDaysFromNow(250), fitness: isoDaysFromNow(40), permit: isoDaysFromNow(150), utilization: 91, purchasedAgency: 'FAW East Africa', vehicleValue: 3600000, emiEnabled: 'Yes', monthlyEMI: 48000, loanBank: 'Dashen Bank' },
    { id: 'V004', regNumber: 'ET-AA-77324', make: 'Volvo', model: 'FH16 (30T)', year: 2019, category: 'Heavy Truck', ownershipType: 'Owned', capacity: '30 Ton', fuelType: 'Diesel', status: 'Maintenance', driverId: 'D004', odometer: 412300, location: { lat: 9.5950, lng: 41.8650, city: 'Dire Dawa' }, speed: 0, lastService: isoDaysFromNow(0), insurance: isoDaysFromNow(60), fitness: isoDaysFromNow(-5), permit: isoDaysFromNow(100), utilization: 55, purchasedAgency: 'Holland Car PLC', vehicleValue: 7900000, emiEnabled: 'Yes', monthlyEMI: 95000, loanBank: 'Awash Bank' },
    { id: 'V005', regNumber: 'ET-SD-33457', make: 'Dongfeng', model: 'KR (12T)', year: 2021, category: 'Medium Truck', ownershipType: 'Owned', capacity: '12 Ton', fuelType: 'Diesel', status: 'Running', driverId: 'D005', odometer: 152800, location: { lat: 7.0500, lng: 38.4760, city: 'Hawassa' }, speed: 58, lastService: isoDaysFromNow(-40), insurance: isoDaysFromNow(170), fitness: isoDaysFromNow(220), permit: isoDaysFromNow(8), utilization: 76, purchasedAgency: 'Dongfeng Ethiopia', vehicleValue: 3100000, emiEnabled: 'No', monthlyEMI: 0, loanBank: 'N/A' },
    { id: 'V006', regNumber: 'ET-AA-99812', make: 'Scania', model: 'R450 (28T)', year: 2023, category: 'Heavy Truck', ownershipType: 'Leased', capacity: '28 Ton', fuelType: 'Diesel', status: 'Idle', driverId: 'D006', odometer: 41200, location: { lat: 9.0192, lng: 38.7468, city: 'Addis Ababa' }, speed: 0, lastService: isoDaysFromNow(-2), insurance: isoDaysFromNow(330), fitness: isoDaysFromNow(300), permit: isoDaysFromNow(290), utilization: 88, purchasedAgency: 'Scania East Africa', vehicleValue: 9200000, emiEnabled: 'Yes', monthlyEMI: 110000, loanBank: 'Bank of Abyssinia' },
    { id: 'V007', regNumber: 'ET-AM-55623', make: 'Toyota', model: 'Hilux (1T)', year: 2022, category: 'Light Commercial', ownershipType: 'Owned', capacity: '1 Ton', fuelType: 'Diesel', status: 'Running', driverId: 'D007', odometer: 67500, location: { lat: 11.5942, lng: 37.3900, city: 'Bahir Dar' }, speed: 80, lastService: isoDaysFromNow(-15), insurance: isoDaysFromNow(45), fitness: isoDaysFromNow(160), permit: isoDaysFromNow(70), utilization: 70, purchasedAgency: 'Toyota Ethiopia', vehicleValue: 1850000, emiEnabled: 'No', monthlyEMI: 0, loanBank: 'N/A' },
    { id: 'V008', regNumber: 'ET-AA-66047', make: 'Isuzu', model: 'NQR (8T)', year: 2018, category: 'Medium Truck', ownershipType: 'Owned', capacity: '8 Ton', fuelType: 'Diesel', status: 'Breakdown', driverId: 'D008', odometer: 388900, location: { lat: 13.4969, lng: 39.4769, city: 'Mekelle' }, speed: 0, lastService: isoDaysFromNow(-60), insurance: isoDaysFromNow(-10), fitness: isoDaysFromNow(15), permit: isoDaysFromNow(55), utilization: 40, purchasedAgency: 'Moenco PLC', vehicleValue: 2400000, emiEnabled: 'No', monthlyEMI: 0, loanBank: 'N/A' },
  ];
  for (const v of vehicles) {
    const { driverId, ...rest } = v;
    await prisma.vehicle.upsert({ where: { id: v.id }, update: {}, create: { ...rest, driverId } });
  }

  // --- Drivers (Ethiopian names, phone format +251) ---
  const drivers = [
    { id: 'D001', name: 'Abebe Kebede', phone: '+251911223344', altPhone: '+251922334455', dob: '1988-04-12', address: 'Bole, Addis Ababa', dlNumber: 'ET-DL-10234', licenseCategory: 'Heavy Truck', licenseExpiry: isoDaysFromNow(180), experience: 12, emergencyContact: '+251933445566', status: 'Active', assignedVehicle: 'V001', fuelScore: 85, safetyScore: 90, onTimeDelivery: 92, customerRating: 4.5, totalTrips: 320, totalKm: 185000, violations: 1, salary: 12000, advance: 1500, attendance: 95, aadhaarNumber: 'FAN-0019283746', panNumber: 'TIN-00198273', supervisorName: 'Tewodros Assefa', supervisorHistory: [] },
    { id: 'D002', name: 'Tigist Alemu', phone: '+251911556677', altPhone: '+251922667788', dob: '1990-09-23', address: 'Kirkos, Addis Ababa', dlNumber: 'ET-DL-10891', licenseCategory: 'Heavy Truck', licenseExpiry: isoDaysFromNow(20), experience: 8, emergencyContact: '+251933778899', status: 'Active', assignedVehicle: 'V002', fuelScore: 78, safetyScore: 88, onTimeDelivery: 85, customerRating: 4.2, totalTrips: 210, totalKm: 132000, violations: 2, salary: 11000, advance: 0, attendance: 91, aadhaarNumber: 'FAN-0028374659', panNumber: 'TIN-00287456', supervisorName: 'Tewodros Assefa', supervisorHistory: [] },
    { id: 'D003', name: 'Dawit Tesfaye', phone: '+251911889900', altPhone: '+251922990011', dob: '1985-01-30', address: 'Adama, Oromia', dlNumber: 'ET-DL-11023', licenseCategory: 'Medium Truck', licenseExpiry: isoDaysFromNow(365), experience: 15, emergencyContact: '+251933001122', status: 'Active', assignedVehicle: 'V003', fuelScore: 91, safetyScore: 94, onTimeDelivery: 96, customerRating: 4.8, totalTrips: 410, totalKm: 240000, violations: 0, salary: 13500, advance: 2000, attendance: 98, aadhaarNumber: 'FAN-0037465819', panNumber: 'TIN-00374651', supervisorName: 'Meron Tadesse', supervisorHistory: [] },
    { id: 'D004', name: 'Hirut Bekele', phone: '+251911112233', altPhone: '+251922223344', dob: '1992-11-05', address: 'Dire Dawa', dlNumber: 'ET-DL-11456', licenseCategory: 'Heavy Truck', licenseExpiry: isoDaysFromNow(-15), experience: 6, emergencyContact: '+251933334455', status: 'Active', assignedVehicle: 'V004', fuelScore: 70, safetyScore: 75, onTimeDelivery: 80, customerRating: 3.9, totalTrips: 140, totalKm: 89000, violations: 3, salary: 10500, advance: 1000, attendance: 87, aadhaarNumber: 'FAN-0046578192', panNumber: 'TIN-00465789', supervisorName: 'Meron Tadesse', supervisorHistory: [] },
    { id: 'D005', name: 'Solomon Girma', phone: '+251911445566', altPhone: '+251922556677', dob: '1987-07-18', address: 'Hawassa, Sidama', dlNumber: 'ET-DL-11789', licenseCategory: 'Medium Truck', licenseExpiry: isoDaysFromNow(500), experience: 10, emergencyContact: '+251933667788', status: 'Active', assignedVehicle: 'V005', fuelScore: 88, safetyScore: 86, onTimeDelivery: 90, customerRating: 4.4, totalTrips: 275, totalKm: 167000, violations: 1, salary: 11800, advance: 500, attendance: 93, aadhaarNumber: 'FAN-0055689203', panNumber: 'TIN-00556892', supervisorName: 'Meron Tadesse', supervisorHistory: [] },
    { id: 'D006', name: 'Meron Tadesse', phone: '+251911778899', altPhone: '+251922889900', dob: '1991-03-27', address: 'Bole, Addis Ababa', dlNumber: 'ET-DL-12012', licenseCategory: 'Heavy Truck', licenseExpiry: isoDaysFromNow(220), experience: 7, emergencyContact: '+251933990011', status: 'Active', assignedVehicle: 'V006', fuelScore: 82, safetyScore: 89, onTimeDelivery: 88, customerRating: 4.3, totalTrips: 198, totalKm: 121000, violations: 1, salary: 12500, advance: 0, attendance: 94, aadhaarNumber: 'FAN-0064792314', panNumber: 'TIN-00647923', supervisorName: 'Tewodros Assefa', supervisorHistory: [] },
    { id: 'D007', name: 'Yonas Haile', phone: '+251911001122', altPhone: '+251922112233', dob: '1995-05-09', address: 'Bahir Dar, Amhara', dlNumber: 'ET-DL-12345', licenseCategory: 'Light Vehicle', licenseExpiry: isoDaysFromNow(150), experience: 4, emergencyContact: '+251933223344', status: 'Active', assignedVehicle: 'V007', fuelScore: 80, safetyScore: 84, onTimeDelivery: 91, customerRating: 4.1, totalTrips: 95, totalKm: 54000, violations: 0, salary: 9500, advance: 0, attendance: 96, aadhaarNumber: 'FAN-0073805425', panNumber: 'TIN-00738054', supervisorName: 'Tewodros Assefa', supervisorHistory: [] },
    { id: 'D008', name: 'Selamawit Mekonnen', phone: '+251911334455', altPhone: '+251922445566', dob: '1989-12-14', address: 'Mekelle, Tigray', dlNumber: 'ET-DL-12678', licenseCategory: 'Medium Truck', licenseExpiry: isoDaysFromNow(35), experience: 9, emergencyContact: '+251933556677', status: 'Inactive', assignedVehicle: 'V008', fuelScore: 65, safetyScore: 72, onTimeDelivery: 75, customerRating: 3.6, totalTrips: 165, totalKm: 102000, violations: 4, salary: 10000, advance: 800, attendance: 80, aadhaarNumber: 'FAN-0082916536', panNumber: 'TIN-00829165', supervisorName: 'Meron Tadesse', supervisorHistory: [] },
  ];
  for (const d of drivers) {
    await prisma.driver.upsert({ where: { id: d.id }, update: {}, create: d });
  }

  // --- Trips (East African corridor routes) ---
  const trips = [
    { id: 'T001', voucherNo: 'VCH-2026-001', origin: 'Addis Ababa', destination: 'Djibouti Port', stops: [], viaStops: ['Adama', 'Dire Dawa'], status: 'In Transit', approvalStatus: 'Approved', rejectionReason: '', driverId: 'D001', vehicleId: 'V001', customer: 'Heineken Brewery Ethiopia', contactPerson: 'Selam Wolde', contactNo: '+251911000111', address: 'Kilinto, Addis Ababa', category: 'FTL', segment: 'FMCG', businessGroup: 'Beverages', employeeId: 'EMP-101', placementDate: isoDaysFromNow(-2), noOfVehicles: 1, vehicleLoadType: 'Full Load', cargo: 'Beverages', content: 'Bottled Beer Cartons', rateType: 'Per Trip', weight: 9500, packages: 1200, rate: 85000, freight: 85000, loadingCharges: 2000, unloadingCharges: 2000, otherCharges: 500, commission: 0, advance: 20000, paymentTerms: '30 Days Credit', creditDays: 30, total: 89500, balance: 69500, volume: 40, plannedDate: isoDaysFromNow(-2), actualDeparture: isoDaysFromNow(-2), eta: isoDaysFromNow(1), distance: 910, approxTimeHrs: 18, plannedKm: 910, actualKm: 620, tollCost: 0, fuelCost: 28000, revenue: 85000, pod: false, delay: 0 },
    { id: 'T002', voucherNo: 'VCH-2026-002', origin: 'Addis Ababa', destination: 'Hawassa', stops: [], viaStops: ['Adama'], status: 'Completed', approvalStatus: 'Approved', rejectionReason: '', driverId: 'D005', vehicleId: 'V005', customer: 'Derba Cement', contactPerson: 'Bekele Worku', contactNo: '+251911000222', address: 'Hawassa Industrial Park', category: 'FTL', segment: 'Construction', businessGroup: 'Cement', employeeId: 'EMP-102', placementDate: isoDaysFromNow(-10), noOfVehicles: 1, vehicleLoadType: 'Full Load', cargo: 'Cement', content: 'Cement Bags 50kg', rateType: 'Per Ton', weight: 12000, packages: 240, rate: 4500, freight: 54000, loadingCharges: 1500, unloadingCharges: 1500, otherCharges: 0, commission: 0, advance: 15000, paymentTerms: '15 Days Credit', creditDays: 15, total: 57000, balance: 0, volume: 30, plannedDate: isoDaysFromNow(-10), actualDeparture: isoDaysFromNow(-10), eta: isoDaysFromNow(-9), distance: 275, approxTimeHrs: 6, plannedKm: 275, actualKm: 280, tollCost: 0, fuelCost: 9500, revenue: 54000, pod: true, delay: 0 },
    { id: 'T003', voucherNo: 'VCH-2026-003', origin: 'Addis Ababa', destination: 'Bahir Dar', stops: [], viaStops: ['Debre Markos'], status: 'Planned', approvalStatus: 'Pending', rejectionReason: '', driverId: 'D007', vehicleId: 'V007', customer: 'Kerchanshe Trading PLC', contactPerson: 'Hanna Girma', contactNo: '+251911000333', address: 'Bahir Dar Warehouse', category: 'PTL', segment: 'Agro Export', businessGroup: 'Coffee', employeeId: 'EMP-103', placementDate: isoDaysFromNow(2), noOfVehicles: 1, vehicleLoadType: 'Part Load', cargo: 'Coffee', content: 'Green Coffee Bean Sacks', rateType: 'Per Trip', weight: 3000, packages: 50, rate: 22000, freight: 22000, loadingCharges: 800, unloadingCharges: 800, otherCharges: 0, commission: 0, advance: 5000, paymentTerms: '7 Days Credit', creditDays: 7, total: 23600, balance: 23600, volume: 12, plannedDate: isoDaysFromNow(2), actualDeparture: null, eta: isoDaysFromNow(3), distance: 565, approxTimeHrs: 11, plannedKm: 565, actualKm: 0, tollCost: 0, fuelCost: 0, revenue: 22000, pod: false, delay: 0 },
    { id: 'T004', voucherNo: 'VCH-2026-004', origin: 'Addis Ababa', destination: 'Mekelle', stops: [], viaStops: ['Dessie', 'Woldiya'], status: 'Delayed', approvalStatus: 'Approved', rejectionReason: '', driverId: 'D008', vehicleId: 'V008', customer: 'National Cement SC', contactPerson: 'Yared Tesfaye', contactNo: '+251911000444', address: 'Mekelle Depot', category: 'FTL', segment: 'Construction', businessGroup: 'Cement', employeeId: 'EMP-104', placementDate: isoDaysFromNow(-4), noOfVehicles: 1, vehicleLoadType: 'Full Load', cargo: 'Cement', content: 'Cement Bags 50kg', rateType: 'Per Ton', weight: 8000, packages: 160, rate: 5200, freight: 41600, loadingCharges: 1200, unloadingCharges: 1200, otherCharges: 1000, commission: 0, advance: 10000, paymentTerms: '15 Days Credit', creditDays: 15, total: 45000, balance: 35000, volume: 22, plannedDate: isoDaysFromNow(-4), actualDeparture: isoDaysFromNow(-4), eta: isoDaysFromNow(-1), distance: 783, approxTimeHrs: 15, plannedKm: 783, actualKm: 540, tollCost: 0, fuelCost: 21000, revenue: 41600, pod: false, delay: 2 },
    { id: 'T005', voucherNo: 'VCH-2026-005', origin: 'Adama', destination: 'Djibouti Port', stops: [], viaStops: ['Dire Dawa'], status: 'Completed', approvalStatus: 'Approved', rejectionReason: '', driverId: 'D003', vehicleId: 'V003', customer: 'Moha Soft Drinks', contactPerson: 'Fitsum Alemu', contactNo: '+251911000555', address: 'Modjo Dry Port', category: 'FTL', segment: 'FMCG', businessGroup: 'Beverages', employeeId: 'EMP-105', placementDate: isoDaysFromNow(-15), noOfVehicles: 1, vehicleLoadType: 'Full Load', cargo: 'Beverages', content: 'Soft Drink Crates', rateType: 'Per Trip', weight: 11000, packages: 1500, rate: 78000, freight: 78000, loadingCharges: 1800, unloadingCharges: 1800, otherCharges: 0, commission: 0, advance: 18000, paymentTerms: '30 Days Credit', creditDays: 30, total: 81600, balance: 0, volume: 38, plannedDate: isoDaysFromNow(-15), actualDeparture: isoDaysFromNow(-15), eta: isoDaysFromNow(-14), distance: 820, approxTimeHrs: 16, plannedKm: 820, actualKm: 825, tollCost: 0, fuelCost: 24500, revenue: 78000, pod: true, delay: 0 },
    { id: 'T006', voucherNo: 'VCH-2026-006', origin: 'Addis Ababa', destination: 'Jimma', stops: [], viaStops: ['Wolkite'], status: 'Cancelled', approvalStatus: 'Rejected', rejectionReason: 'Customer cancelled pickup', driverId: null, vehicleId: null, customer: 'Habesha Breweries', contactPerson: 'Lulit Demissie', contactNo: '+251911000666', address: 'Jimma Distribution Center', category: 'FTL', segment: 'FMCG', businessGroup: 'Beverages', employeeId: 'EMP-106', placementDate: isoDaysFromNow(-6), noOfVehicles: 1, vehicleLoadType: 'Full Load', cargo: 'Beverages', content: 'Bottled Beer Cartons', rateType: 'Per Trip', weight: 9000, packages: 1100, rate: 60000, freight: 60000, loadingCharges: 0, unloadingCharges: 0, otherCharges: 0, commission: 0, advance: 0, paymentTerms: '30 Days Credit', creditDays: 30, total: 60000, balance: 60000, volume: 35, plannedDate: isoDaysFromNow(-6), actualDeparture: null, eta: isoDaysFromNow(-5), distance: 350, approxTimeHrs: 7, plannedKm: 350, actualKm: 0, tollCost: 0, fuelCost: 0, revenue: 0, pod: false, delay: 0 },
    { id: 'T007', voucherNo: 'VCH-2026-007', origin: 'Addis Ababa', destination: 'Gondar', stops: [], viaStops: ['Debre Markos', 'Bahir Dar'], status: 'In Transit', approvalStatus: 'Approved', rejectionReason: '', driverId: 'D006', vehicleId: 'V006', customer: 'Ethio Telecom Logistics', contactPerson: 'Mekdes Asfaw', contactNo: '+251911000777', address: 'Gondar Regional Office', category: 'FTL', segment: 'Industrial', businessGroup: 'Telecom Equipment', employeeId: 'EMP-107', placementDate: isoDaysFromNow(-1), noOfVehicles: 1, vehicleLoadType: 'Full Load', cargo: 'Equipment', content: 'Network Tower Parts', rateType: 'Per Trip', weight: 14000, packages: 80, rate: 92000, freight: 92000, loadingCharges: 2500, unloadingCharges: 2500, otherCharges: 0, commission: 0, advance: 25000, paymentTerms: '30 Days Credit', creditDays: 30, total: 97000, balance: 72000, volume: 45, plannedDate: isoDaysFromNow(-1), actualDeparture: isoDaysFromNow(-1), eta: isoDaysFromNow(1), distance: 738, approxTimeHrs: 14, plannedKm: 738, actualKm: 400, tollCost: 0, fuelCost: 19000, revenue: 92000, pod: false, delay: 0 },
    { id: 'T008', voucherNo: 'VCH-2026-008', origin: 'Dire Dawa', destination: 'Djibouti Port', stops: [], viaStops: [], status: 'Completed', approvalStatus: 'Approved', rejectionReason: '', driverId: 'D004', vehicleId: 'V004', customer: 'Dangote Cement Ethiopia', contactPerson: 'Ahmed Nuru', contactNo: '+251911000888', address: 'Djibouti Free Zone', category: 'FTL', segment: 'Construction', businessGroup: 'Cement', employeeId: 'EMP-108', placementDate: isoDaysFromNow(-20), noOfVehicles: 1, vehicleLoadType: 'Full Load', cargo: 'Cement', content: 'Cement Bags 50kg', rateType: 'Per Ton', weight: 20000, packages: 400, rate: 3800, freight: 76000, loadingCharges: 2200, unloadingCharges: 2200, otherCharges: 0, commission: 0, advance: 22000, paymentTerms: '15 Days Credit', creditDays: 15, total: 80400, balance: 0, volume: 55, plannedDate: isoDaysFromNow(-20), actualDeparture: isoDaysFromNow(-20), eta: isoDaysFromNow(-19), distance: 310, approxTimeHrs: 6, plannedKm: 310, actualKm: 312, tollCost: 0, fuelCost: 11500, revenue: 76000, pod: true, delay: 0 },
    // Older completed trips spread across the last 6 months, for dashboard/trend charts
    { id: 'T009', voucherNo: 'VCH-2025-109', origin: 'Addis Ababa', destination: 'Hawassa', stops: [], viaStops: ['Adama'], status: 'Completed', approvalStatus: 'Approved', rejectionReason: '', driverId: 'D002', vehicleId: 'V002', customer: 'Habesha Breweries', contactPerson: 'Lulit Demissie', contactNo: '+251911000666', address: 'Hawassa Distribution Center', category: 'FTL', segment: 'FMCG', businessGroup: 'Beverages', employeeId: 'EMP-106', placementDate: isoDaysFromNow(-210), noOfVehicles: 1, vehicleLoadType: 'Full Load', cargo: 'Beverages', content: 'Bottled Beer Cartons', rateType: 'Per Trip', weight: 9200, packages: 1150, rate: 58000, freight: 58000, loadingCharges: 1600, unloadingCharges: 1600, otherCharges: 0, commission: 0, advance: 15000, paymentTerms: '30 Days Credit', creditDays: 30, total: 61200, balance: 0, volume: 36, plannedDate: isoDaysFromNow(-210), actualDeparture: isoDaysFromNow(-210), eta: isoDaysFromNow(-209), distance: 275, approxTimeHrs: 6, plannedKm: 275, actualKm: 278, tollCost: 180, fuelCost: 9300, revenue: 58000, pod: true, delay: 0 },
    { id: 'T010', voucherNo: 'VCH-2025-110', origin: 'Addis Ababa', destination: 'Djibouti Port', stops: [], viaStops: ['Adama', 'Dire Dawa'], status: 'Completed', approvalStatus: 'Approved', rejectionReason: '', driverId: 'D004', vehicleId: 'V004', customer: 'Dangote Cement Ethiopia', contactPerson: 'Ahmed Nuru', contactNo: '+251911000888', address: 'Djibouti Free Zone', category: 'FTL', segment: 'Construction', businessGroup: 'Cement', employeeId: 'EMP-108', placementDate: isoDaysFromNow(-180), noOfVehicles: 1, vehicleLoadType: 'Full Load', cargo: 'Cement', content: 'Cement Bags 50kg', rateType: 'Per Ton', weight: 21000, packages: 420, rate: 3850, freight: 81000, loadingCharges: 2300, unloadingCharges: 2300, otherCharges: 0, commission: 0, advance: 20000, paymentTerms: '15 Days Credit', creditDays: 15, total: 85600, balance: 0, volume: 56, plannedDate: isoDaysFromNow(-180), actualDeparture: isoDaysFromNow(-180), eta: isoDaysFromNow(-179), distance: 910, approxTimeHrs: 18, plannedKm: 910, actualKm: 915, tollCost: 270, fuelCost: 29500, revenue: 81000, pod: true, delay: 0 },
    { id: 'T011', voucherNo: 'VCH-2026-111', origin: 'Adama', destination: 'Djibouti Port', stops: [], viaStops: ['Dire Dawa'], status: 'Completed', approvalStatus: 'Approved', rejectionReason: '', driverId: 'D006', vehicleId: 'V006', customer: 'Moha Soft Drinks', contactPerson: 'Fitsum Alemu', contactNo: '+251911000555', address: 'Modjo Dry Port', category: 'FTL', segment: 'FMCG', businessGroup: 'Beverages', employeeId: 'EMP-105', placementDate: isoDaysFromNow(-150), noOfVehicles: 1, vehicleLoadType: 'Full Load', cargo: 'Beverages', content: 'Soft Drink Crates', rateType: 'Per Trip', weight: 10800, packages: 1450, rate: 76000, freight: 76000, loadingCharges: 1750, unloadingCharges: 1750, otherCharges: 0, commission: 0, advance: 18000, paymentTerms: '30 Days Credit', creditDays: 30, total: 79500, balance: 0, volume: 37, plannedDate: isoDaysFromNow(-150), actualDeparture: isoDaysFromNow(-150), eta: isoDaysFromNow(-149), distance: 820, approxTimeHrs: 16, plannedKm: 820, actualKm: 818, tollCost: 180, fuelCost: 24000, revenue: 76000, pod: true, delay: 0 },
    { id: 'T012', voucherNo: 'VCH-2026-112', origin: 'Addis Ababa', destination: 'Bahir Dar', stops: [], viaStops: ['Debre Markos'], status: 'Completed', approvalStatus: 'Approved', rejectionReason: '', driverId: 'D007', vehicleId: 'V007', customer: 'Kerchanshe Trading PLC', contactPerson: 'Hanna Girma', contactNo: '+251911000333', address: 'Bahir Dar Warehouse', category: 'PTL', segment: 'Agro Export', businessGroup: 'Coffee', employeeId: 'EMP-103', placementDate: isoDaysFromNow(-120), noOfVehicles: 1, vehicleLoadType: 'Part Load', cargo: 'Coffee', content: 'Green Coffee Bean Sacks', rateType: 'Per Trip', weight: 3200, packages: 55, rate: 24000, freight: 24000, loadingCharges: 850, unloadingCharges: 850, otherCharges: 0, commission: 0, advance: 6000, paymentTerms: '7 Days Credit', creditDays: 7, total: 25700, balance: 0, volume: 13, plannedDate: isoDaysFromNow(-120), actualDeparture: isoDaysFromNow(-120), eta: isoDaysFromNow(-119), distance: 565, approxTimeHrs: 11, plannedKm: 565, actualKm: 570, tollCost: 0, fuelCost: 7800, revenue: 24000, pod: true, delay: 0 },
    { id: 'T013', voucherNo: 'VCH-2026-113', origin: 'Addis Ababa', destination: 'Mekelle', stops: [], viaStops: ['Dessie', 'Woldiya'], status: 'Completed', approvalStatus: 'Approved', rejectionReason: '', driverId: 'D008', vehicleId: 'V008', customer: 'National Cement SC', contactPerson: 'Yared Tesfaye', contactNo: '+251911000444', address: 'Mekelle Depot', category: 'FTL', segment: 'Construction', businessGroup: 'Cement', employeeId: 'EMP-104', placementDate: isoDaysFromNow(-90), noOfVehicles: 1, vehicleLoadType: 'Full Load', cargo: 'Cement', content: 'Cement Bags 50kg', rateType: 'Per Ton', weight: 8200, packages: 164, rate: 5300, freight: 43000, loadingCharges: 1250, unloadingCharges: 1250, otherCharges: 0, commission: 0, advance: 10000, paymentTerms: '15 Days Credit', creditDays: 15, total: 45500, balance: 0, volume: 23, plannedDate: isoDaysFromNow(-90), actualDeparture: isoDaysFromNow(-90), eta: isoDaysFromNow(-89), distance: 783, approxTimeHrs: 15, plannedKm: 783, actualKm: 788, tollCost: 0, fuelCost: 14200, revenue: 43000, pod: true, delay: 0 },
    { id: 'T014', voucherNo: 'VCH-2026-114', origin: 'Addis Ababa', destination: 'Gondar', stops: [], viaStops: ['Debre Markos', 'Bahir Dar'], status: 'Completed', approvalStatus: 'Approved', rejectionReason: '', driverId: 'D001', vehicleId: 'V001', customer: 'Ethio Telecom Logistics', contactPerson: 'Mekdes Asfaw', contactNo: '+251911000777', address: 'Gondar Regional Office', category: 'FTL', segment: 'Industrial', businessGroup: 'Telecom Equipment', employeeId: 'EMP-107', placementDate: isoDaysFromNow(-60), noOfVehicles: 1, vehicleLoadType: 'Full Load', cargo: 'Equipment', content: 'Network Tower Parts', rateType: 'Per Trip', weight: 13500, packages: 75, rate: 89000, freight: 89000, loadingCharges: 2400, unloadingCharges: 2400, otherCharges: 0, commission: 0, advance: 24000, paymentTerms: '30 Days Credit', creditDays: 30, total: 93800, balance: 0, volume: 44, plannedDate: isoDaysFromNow(-60), actualDeparture: isoDaysFromNow(-60), eta: isoDaysFromNow(-59), distance: 738, approxTimeHrs: 14, plannedKm: 738, actualKm: 742, tollCost: 0, fuelCost: 18200, revenue: 89000, pod: true, delay: 0 },
    { id: 'T015', voucherNo: 'VCH-2026-115', origin: 'Addis Ababa', destination: 'Jimma', stops: [], viaStops: ['Wolkite'], status: 'Completed', approvalStatus: 'Approved', rejectionReason: '', driverId: 'D003', vehicleId: 'V003', customer: 'Habesha Breweries', contactPerson: 'Lulit Demissie', contactNo: '+251911000666', address: 'Jimma Distribution Center', category: 'FTL', segment: 'FMCG', businessGroup: 'Beverages', employeeId: 'EMP-106', placementDate: isoDaysFromNow(-45), noOfVehicles: 1, vehicleLoadType: 'Full Load', cargo: 'Beverages', content: 'Bottled Beer Cartons', rateType: 'Per Trip', weight: 9100, packages: 1120, rate: 61000, freight: 61000, loadingCharges: 1650, unloadingCharges: 1650, otherCharges: 0, commission: 0, advance: 15000, paymentTerms: '30 Days Credit', creditDays: 30, total: 64300, balance: 0, volume: 35, plannedDate: isoDaysFromNow(-45), actualDeparture: isoDaysFromNow(-45), eta: isoDaysFromNow(-44), distance: 350, approxTimeHrs: 7, plannedKm: 350, actualKm: 353, tollCost: 0, fuelCost: 10800, revenue: 61000, pod: true, delay: 0 },
    { id: 'T016', voucherNo: 'VCH-2026-116', origin: 'Dire Dawa', destination: 'Djibouti Port', stops: [], viaStops: [], status: 'Completed', approvalStatus: 'Approved', rejectionReason: '', driverId: 'D005', vehicleId: 'V005', customer: 'Dangote Cement Ethiopia', contactPerson: 'Ahmed Nuru', contactNo: '+251911000888', address: 'Djibouti Free Zone', category: 'FTL', segment: 'Construction', businessGroup: 'Cement', employeeId: 'EMP-108', placementDate: isoDaysFromNow(-30), noOfVehicles: 1, vehicleLoadType: 'Full Load', cargo: 'Cement', content: 'Cement Bags 50kg', rateType: 'Per Ton', weight: 19500, packages: 390, rate: 3850, freight: 79000, loadingCharges: 2150, unloadingCharges: 2150, otherCharges: 0, commission: 0, advance: 20000, paymentTerms: '15 Days Credit', creditDays: 15, total: 83300, balance: 0, volume: 54, plannedDate: isoDaysFromNow(-30), actualDeparture: isoDaysFromNow(-30), eta: isoDaysFromNow(-29), distance: 310, approxTimeHrs: 6, plannedKm: 310, actualKm: 308, tollCost: 0, fuelCost: 11200, revenue: 79000, pod: true, delay: 0 },
  ];
  for (const t of trips) {
    await prisma.trip.upsert({ where: { id: t.id }, update: {}, create: t });
  }

  // --- Fuel entries ---
  const fuelEntries = [
    { id: 'F001', vehicleId: 'V001', date: isoDaysFromNow(-2), liters: 180, pricePerLiter: 64.5, totalCost: 11610, odometer: 184230, kmpl: 4.2, station: 'NOC Bole Station', fuelCardUsed: true, tripId: 'T001' },
    { id: 'F002', vehicleId: 'V003', date: isoDaysFromNow(-15), liters: 150, pricePerLiter: 64.5, totalCost: 9675, odometer: 97900, kmpl: 4.8, station: 'TotalEnergies Adama', fuelCardUsed: true, tripId: 'T005' },
    { id: 'F003', vehicleId: 'V005', date: isoDaysFromNow(-10), liters: 95, pricePerLiter: 64.5, totalCost: 6127, odometer: 152600, kmpl: 5.1, station: 'Oilibya Hawassa', fuelCardUsed: false, tripId: 'T002' },
    { id: 'F004', vehicleId: 'V008', date: isoDaysFromNow(-4), liters: 110, pricePerLiter: 64.5, totalCost: 7095, odometer: 388700, kmpl: 3.6, station: 'NOC Mekelle', fuelCardUsed: true, tripId: 'T004' },
    { id: 'F005', vehicleId: 'V006', date: isoDaysFromNow(-1), liters: 200, pricePerLiter: 64.5, totalCost: 12900, odometer: 41100, kmpl: 4.5, station: 'NOC Bole Station', fuelCardUsed: true, tripId: 'T007' },
    { id: 'F006', vehicleId: 'V004', date: isoDaysFromNow(-20), liters: 175, pricePerLiter: 63.8, totalCost: 11165, odometer: 411900, kmpl: 4.0, station: 'TotalEnergies Dire Dawa', fuelCardUsed: true, tripId: 'T008' },
    { id: 'F007', vehicleId: 'V002', date: isoDaysFromNow(-8), liters: 220, pricePerLiter: 64.5, totalCost: 14190, odometer: 256100, kmpl: 3.9, station: 'NOC Bole Station', fuelCardUsed: false, tripId: null },
    { id: 'F008', vehicleId: 'V007', date: isoDaysFromNow(-3), liters: 60, pricePerLiter: 64.5, totalCost: 3870, odometer: 67300, kmpl: 7.2, station: 'Oilibya Bahir Dar', fuelCardUsed: true, tripId: null },
    { id: 'F009', vehicleId: 'V002', date: isoDaysFromNow(-210), liters: 145, pricePerLiter: 64.1, totalCost: 9295, odometer: 198400, kmpl: 4.6, station: 'Oilibya Hawassa', fuelCardUsed: true, tripId: 'T009' },
    { id: 'F010', vehicleId: 'V004', date: isoDaysFromNow(-180), liters: 462, pricePerLiter: 63.8, totalCost: 29500, odometer: 365200, kmpl: 4.1, station: 'TotalEnergies Dire Dawa', fuelCardUsed: true, tripId: 'T010' },
    { id: 'F011', vehicleId: 'V006', date: isoDaysFromNow(-150), liters: 374, pricePerLiter: 64.2, totalCost: 24000, odometer: 28900, kmpl: 4.4, station: 'NOC Bole Station', fuelCardUsed: true, tripId: 'T011' },
    { id: 'F012', vehicleId: 'V007', date: isoDaysFromNow(-120), liters: 121, pricePerLiter: 64.5, totalCost: 7800, odometer: 51200, kmpl: 7.0, station: 'Oilibya Bahir Dar', fuelCardUsed: true, tripId: 'T012' },
    { id: 'F013', vehicleId: 'V008', date: isoDaysFromNow(-90), liters: 219, pricePerLiter: 64.8, totalCost: 14200, odometer: 360100, kmpl: 3.6, station: 'NOC Mekelle', fuelCardUsed: true, tripId: 'T013' },
    { id: 'F014', vehicleId: 'V001', date: isoDaysFromNow(-60), liters: 282, pricePerLiter: 64.5, totalCost: 18200, odometer: 165800, kmpl: 4.1, station: 'NOC Bole Station', fuelCardUsed: true, tripId: 'T014' },
    { id: 'F015', vehicleId: 'V003', date: isoDaysFromNow(-45), liters: 167, pricePerLiter: 64.7, totalCost: 10800, odometer: 75100, kmpl: 4.7, station: 'TotalEnergies Adama', fuelCardUsed: true, tripId: 'T015' },
    { id: 'F016', vehicleId: 'V005', date: isoDaysFromNow(-30), liters: 173, pricePerLiter: 64.7, totalCost: 11200, odometer: 145200, kmpl: 5.0, station: 'TotalEnergies Dire Dawa', fuelCardUsed: true, tripId: 'T016' },
  ];
  for (const f of fuelEntries) {
    await prisma.fuelEntry.upsert({ where: { id: f.id }, update: {}, create: f });
  }

  // --- Maintenance records ---
  const maintenanceRecords = [
    { id: 'M001', vehicleId: 'V004', type: 'Breakdown', description: 'Engine overheating, coolant leak', date: isoDaysFromNow(0), status: 'In Progress', cost: 18500, vendor: 'Holland Car Service Center', estimatedCompletion: isoDaysFromNow(3), parts: [{ name: 'Radiator', qty: 1, cost: 9500 }, { name: 'Coolant 5L', qty: 2, cost: 1200 }] },
    { id: 'M002', vehicleId: 'V008', type: 'Breakdown', description: 'Gearbox failure', date: isoDaysFromNow(-1), status: 'In Progress', cost: 32000, vendor: 'Moenco Service Center', estimatedCompletion: isoDaysFromNow(5), parts: [{ name: 'Clutch Plate', qty: 1, cost: 14000 }] },
    { id: 'M003', vehicleId: 'V001', type: 'Preventive', description: 'Scheduled 5000km service', date: isoDaysFromNow(-25), status: 'Completed', cost: 4200, vendor: 'Moenco Service Center', estimatedCompletion: isoDaysFromNow(-24), parts: [{ name: 'Engine Oil 15L', qty: 1, cost: 2400 }, { name: 'Oil Filter', qty: 1, cost: 350 }] },
    { id: 'M004', vehicleId: 'V003', type: 'Tyre', description: 'Front tyre replacement', date: isoDaysFromNow(-5), status: 'Completed', cost: 16800, vendor: 'Ethio Truck Service', estimatedCompletion: isoDaysFromNow(-5), parts: [{ name: 'Bridgestone Tyre 12R22.5', qty: 2, cost: 8000 }] },
    { id: 'M005', vehicleId: 'V002', type: 'Preventive', description: 'Brake pad inspection and replacement', date: isoDaysFromNow(-12), status: 'Completed', cost: 5600, vendor: 'Ethio Truck Service', estimatedCompletion: isoDaysFromNow(-12), parts: [{ name: 'Brake Pad Set', qty: 1, cost: 3200 }] },
    { id: 'M006', vehicleId: 'V006', type: 'Preventive', description: 'AC system service', date: isoDaysFromNow(-2), status: 'Completed', cost: 2800, vendor: 'Holland Car Service Center', estimatedCompletion: isoDaysFromNow(-2), parts: [{ name: 'AC Gas Refill', qty: 1, cost: 1500 }] },
  ];
  for (const m of maintenanceRecords) {
    await prisma.maintenanceRecord.upsert({ where: { id: m.id }, update: {}, create: m });
  }

  // --- Compliance records (one per vehicle; expiries vary so Alerts auto-populate) ---
  const complianceRecords = vehicles.map((v) => ({
    vehicleId: v.id,
    rc: { number: `RC-${v.id}`, issueDate: '2018-01-15', expiryDate: isoDaysFromNow(700), status: 'Valid' },
    insurance: { number: `INS-${v.id}`, issueDate: isoDaysFromNow(-200), expiryDate: v.insurance, status: new Date(v.insurance) < today ? 'Expired' : 'Valid' },
    fitness: { number: `FIT-${v.id}`, issueDate: isoDaysFromNow(-300), expiryDate: v.fitness, status: new Date(v.fitness) < today ? 'Expired' : 'Valid' },
    pollution: { number: `POL-${v.id}`, issueDate: isoDaysFromNow(-150), expiryDate: isoDaysFromNow(120), status: 'Valid' },
    statePermit: { number: `SP-${v.id}`, issueDate: isoDaysFromNow(-400), expiryDate: v.permit, status: new Date(v.permit) < today ? 'Expired' : 'Valid' },
    nationalPermit: { number: `NP-${v.id}`, issueDate: isoDaysFromNow(-400), expiryDate: isoDaysFromNow(365), status: 'Valid' },
  }));
  for (const c of complianceRecords) {
    await prisma.complianceRecord.upsert({ where: { vehicleId: c.vehicleId }, update: {}, create: c });
  }

  // --- Consignments ---
  const consignments = [
    { id: 'CN001', cnNumber: 'CN-2026-001', cnDate: isoDaysFromNow(-2), docType: 'Consignment Note', against: 'Trip', againstNo: 'T001', vehicleId: 'V001', source: 'Addis Ababa', destination: 'Djibouti Port', consignor: 'Heineken Brewery Ethiopia', consignorLocation: 'Kilinto, Addis Ababa', consignorGstin: 'ET-TIN-100234567', consignee: 'Djibouti Distribution SARL', consigneeLocation: 'Djibouti City', consigneeGstin: 'DJ-TIN-200998877', billingParty: 'Heineken Brewery Ethiopia', billingPartyLocation: 'Kilinto, Addis Ababa', billingPartyGstin: 'ET-TIN-100234567', deliveryAt: 'Djibouti Port Warehouse 4', loadType: 'Full Load', paymentTerms: '30 Days Credit', mode: 'Road', godown: 'Kilinto Warehouse', containerNo: 'N/A', sealNo: 'SL-88231', markNo: 'HB-2026', expectedDelivery: isoDaysFromNow(1), transporter: 'FMS1 Logistics', items: [{ desc: 'Bottled Beer Cartons', qty: 1200, weight: 9500 }], totalWeight: 9500, totalFreight: 85000, createdBy: 'U003' },
    { id: 'CN002', cnNumber: 'CN-2026-002', cnDate: isoDaysFromNow(-10), docType: 'Consignment Note', against: 'Trip', againstNo: 'T002', vehicleId: 'V005', source: 'Addis Ababa', destination: 'Hawassa', consignor: 'Derba Cement', consignorLocation: 'Derba, Oromia', consignorGstin: 'ET-TIN-100445566', consignee: 'Hawassa Industrial Park', consigneeLocation: 'Hawassa', consigneeGstin: 'ET-TIN-100778899', billingParty: 'Derba Cement', billingPartyLocation: 'Derba, Oromia', billingPartyGstin: 'ET-TIN-100445566', deliveryAt: 'Hawassa Industrial Park Gate 2', loadType: 'Full Load', paymentTerms: '15 Days Credit', mode: 'Road', godown: 'Derba Plant Yard', containerNo: 'N/A', sealNo: 'SL-77120', markNo: 'DC-2026', expectedDelivery: isoDaysFromNow(-9), transporter: 'FMS1 Logistics', items: [{ desc: 'Cement Bags 50kg', qty: 240, weight: 12000 }], totalWeight: 12000, totalFreight: 54000, createdBy: 'U003' },
    { id: 'CN003', cnNumber: 'CN-2026-003', cnDate: isoDaysFromNow(-15), docType: 'Consignment Note', against: 'Trip', againstNo: 'T005', vehicleId: 'V003', source: 'Adama', destination: 'Djibouti Port', consignor: 'Moha Soft Drinks', consignorLocation: 'Modjo Dry Port', consignorGstin: 'ET-TIN-100556677', consignee: 'Djibouti Distribution SARL', consigneeLocation: 'Djibouti City', consigneeGstin: 'DJ-TIN-200998877', billingParty: 'Moha Soft Drinks', billingPartyLocation: 'Modjo Dry Port', billingPartyGstin: 'ET-TIN-100556677', deliveryAt: 'Djibouti Port Warehouse 2', loadType: 'Full Load', paymentTerms: '30 Days Credit', mode: 'Road', godown: 'Modjo Warehouse', containerNo: 'N/A', sealNo: 'SL-66541', markNo: 'MS-2026', expectedDelivery: isoDaysFromNow(-14), transporter: 'FMS1 Logistics', items: [{ desc: 'Soft Drink Crates', qty: 1500, weight: 11000 }], totalWeight: 11000, totalFreight: 78000, createdBy: 'U002' },
    { id: 'CN004', cnNumber: 'CN-2026-004', cnDate: isoDaysFromNow(-1), docType: 'Consignment Note', against: 'Trip', againstNo: 'T007', vehicleId: 'V006', source: 'Addis Ababa', destination: 'Gondar', consignor: 'Ethio Telecom Logistics', consignorLocation: 'CMC, Addis Ababa', consignorGstin: 'ET-TIN-100887766', consignee: 'Ethio Telecom Regional Office', consigneeLocation: 'Gondar', consigneeGstin: 'ET-TIN-100998811', billingParty: 'Ethio Telecom Logistics', billingPartyLocation: 'CMC, Addis Ababa', billingPartyGstin: 'ET-TIN-100887766', deliveryAt: 'Gondar Regional Office', loadType: 'Full Load', paymentTerms: '30 Days Credit', mode: 'Road', godown: 'CMC Central Warehouse', containerNo: 'N/A', sealNo: 'SL-55982', markNo: 'ET-2026', expectedDelivery: isoDaysFromNow(1), transporter: 'FMS1 Logistics', items: [{ desc: 'Network Tower Parts', qty: 80, weight: 14000 }], totalWeight: 14000, totalFreight: 92000, createdBy: 'U003' },
  ];
  for (const c of consignments) {
    await prisma.consignment.upsert({ where: { id: c.id }, update: {}, create: c });
  }

  // --- Petty cash ---
  const pettyCash = [
    { id: 'PC001', tripId: 'T001', driverId: 'D001', driverName: 'Abebe Kebede', tripRoute: 'Addis Ababa → Djibouti Port', issueDate: isoDaysFromNow(-2), cashIssued: 8000, expenses: [{ type: 'Toll', amount: 0 }, { type: 'Food', amount: 1200 }, { type: 'Parking', amount: 300 }], totalSpent: 1500, balance: 6500, status: 'Pending Settlement', settledDate: null, notes: 'Border crossing fees pending', transferStatus: 'Completed', transferAmount: 8000, transferMode: 'Bank Transfer' },
    { id: 'PC002', tripId: 'T002', driverId: 'D005', driverName: 'Solomon Girma', tripRoute: 'Addis Ababa → Hawassa', issueDate: isoDaysFromNow(-10), cashIssued: 3000, expenses: [{ type: 'Food', amount: 600 }, { type: 'Parking', amount: 200 }], totalSpent: 800, balance: 2200, status: 'Settled', settledDate: isoDaysFromNow(-9), notes: '', transferStatus: 'Completed', transferAmount: 3000, transferMode: 'Mobile Money' },
    { id: 'PC003', tripId: 'T004', driverId: 'D008', driverName: 'Selamawit Mekonnen', tripRoute: 'Addis Ababa → Mekelle', issueDate: isoDaysFromNow(-4), cashIssued: 6000, expenses: [{ type: 'Food', amount: 900 }, { type: 'Breakdown Assistance', amount: 2500 }], totalSpent: 3400, balance: 2600, status: 'Pending Settlement', settledDate: null, notes: 'Delay due to road diversion', transferStatus: 'Completed', transferAmount: 6000, transferMode: 'Bank Transfer' },
    { id: 'PC004', tripId: 'T007', driverId: 'D006', driverName: 'Meron Tadesse', tripRoute: 'Addis Ababa → Gondar', issueDate: isoDaysFromNow(-1), cashIssued: 5500, expenses: [{ type: 'Food', amount: 700 }], totalSpent: 700, balance: 4800, status: 'Pending Settlement', settledDate: null, notes: '', transferStatus: 'Completed', transferAmount: 5500, transferMode: 'Mobile Money' },
  ];
  for (const p of pettyCash) {
    await prisma.pettyCash.upsert({ where: { id: p.id }, update: {}, create: p });
  }

  // --- Prepaid toll accounts (Addis Ababa–Adama Expressway) ---
  const fastagAccounts = [
    { vehicleId: 'V001', regNumber: 'ET-AA-23715', fastagId: 'TOLL-AA-00123', bank: 'Commercial Bank of Ethiopia', balance: 4500, status: 'Active', lastTransaction: isoDaysFromNow(-2) },
    { vehicleId: 'V003', regNumber: 'ET-OR-11296', fastagId: 'TOLL-AA-00456', bank: 'Dashen Bank', balance: 1200, status: 'Low Balance', lastTransaction: isoDaysFromNow(-1) },
    { vehicleId: 'V005', regNumber: 'ET-SD-33457', fastagId: 'TOLL-AA-00789', bank: 'Awash Bank', balance: 3200, status: 'Active', lastTransaction: isoDaysFromNow(-3) },
    { vehicleId: 'V006', regNumber: 'ET-AA-99812', fastagId: 'TOLL-AA-01012', bank: 'Bank of Abyssinia', balance: 0, status: 'Inactive', lastTransaction: isoDaysFromNow(-25) },
  ];
  for (const a of fastagAccounts) {
    await prisma.fastagAccount.upsert({ where: { vehicleId: a.vehicleId }, update: {}, create: a });
  }
  const fastagTransactions = [
    { txnId: 'TXN001', vehicleId: 'V001', regNumber: 'ET-AA-23715', bank: 'Commercial Bank of Ethiopia', plaza: 'Adama Tollgate', highway: 'Addis Ababa–Adama Expressway', amount: 180, timestamp: isoDaysFromNow(-2), tripId: 'T001', matched: true },
    { txnId: 'TXN002', vehicleId: 'V001', regNumber: 'ET-AA-23715', bank: 'Commercial Bank of Ethiopia', plaza: 'Bishoftu Tollgate', highway: 'Addis Ababa–Adama Expressway', amount: 90, timestamp: isoDaysFromNow(-2), tripId: 'T001', matched: true },
    { txnId: 'TXN003', vehicleId: 'V003', regNumber: 'ET-OR-11296', bank: 'Dashen Bank', plaza: 'Mojo Tollgate', highway: 'Addis Ababa–Adama Expressway', amount: 90, timestamp: isoDaysFromNow(-15), tripId: 'T005', matched: true },
    { txnId: 'TXN004', vehicleId: 'V005', regNumber: 'ET-SD-33457', bank: 'Awash Bank', plaza: 'Adama Tollgate', highway: 'Addis Ababa–Adama Expressway', amount: 180, timestamp: isoDaysFromNow(-10), tripId: 'T002', matched: false },
    { txnId: 'TXN005', vehicleId: 'V006', regNumber: 'ET-AA-99812', bank: 'Bank of Abyssinia', plaza: 'Bishoftu Tollgate', highway: 'Addis Ababa–Adama Expressway', amount: 90, timestamp: isoDaysFromNow(-1), tripId: 'T007', matched: false },
  ];
  for (const t of fastagTransactions) {
    await prisma.fastagTransaction.upsert({ where: { txnId: t.txnId }, update: {}, create: t });
  }

  // --- Payout pool (singleton) ---
  await prisma.payoutPool.upsert({
    where: { id: 'singleton' },
    update: { totalLoaded: 200000, balance: 148000 },
    create: { id: 'singleton', totalLoaded: 200000, balance: 148000, lowBalanceThreshold: 50000 },
  });

  // --- Spare parts + ledger ---
  const spareParts = [
    { id: 'SP001', partNo: 'BRK-PAD-01', name: 'Brake Pad Set', category: 'Brakes', unit: 'Set', currentStock: 14, reorderLevel: 5, unitPrice: 3200, vendor: 'Ethio Truck Service', location: 'Addis Ababa Main Store' },
    { id: 'SP002', partNo: 'OIL-FLT-01', name: 'Oil Filter', category: 'Engine', unit: 'Piece', currentStock: 32, reorderLevel: 10, unitPrice: 350, vendor: 'Moenco PLC', location: 'Addis Ababa Main Store' },
    { id: 'SP003', partNo: 'TYR-BS-12R', name: 'Bridgestone Tyre 12R22.5', category: 'Tyres', unit: 'Piece', currentStock: 8, reorderLevel: 4, unitPrice: 8000, vendor: 'Bridgestone Ethiopia', location: 'Adama Sub Store' },
    { id: 'SP004', partNo: 'COOL-RAD-01', name: 'Radiator', category: 'Cooling', unit: 'Piece', currentStock: 2, reorderLevel: 3, unitPrice: 9500, vendor: 'Holland Car PLC', location: 'Addis Ababa Main Store' },
    { id: 'SP005', partNo: 'CLT-PLT-01', name: 'Clutch Plate', category: 'Transmission', unit: 'Piece', currentStock: 5, reorderLevel: 3, unitPrice: 14000, vendor: 'Moenco PLC', location: 'Addis Ababa Main Store' },
    { id: 'SP006', partNo: 'BAT-12V-01', name: 'Truck Battery 12V 200Ah', category: 'Electrical', unit: 'Piece', currentStock: 6, reorderLevel: 4, unitPrice: 6200, vendor: 'Ethio Truck Service', location: 'Adama Sub Store' },
  ];
  for (const s of spareParts) {
    await prisma.sparePart.upsert({ where: { id: s.id }, update: {}, create: s });
  }
  const spareLedger = [
    { id: 'SL001', partId: 'SP004', partName: 'Radiator', type: 'Issue', quantity: 1, date: isoDaysFromNow(0), vehicleId: 'V004', regNumber: 'ET-AA-77324', reference: 'M001', vendor: null, unitPrice: 9500, notes: 'Used for breakdown repair', balanceAfter: 2, performedBy: 'Priya Sharma' },
    { id: 'SL002', partId: 'SP005', partName: 'Clutch Plate', type: 'Issue', quantity: 1, date: isoDaysFromNow(-1), vehicleId: 'V008', regNumber: 'ET-AA-66047', reference: 'M002', vendor: null, unitPrice: 14000, notes: 'Gearbox repair', balanceAfter: 5, performedBy: 'Priya Sharma' },
    { id: 'SL003', partId: 'SP003', partName: 'Bridgestone Tyre 12R22.5', type: 'Issue', quantity: 2, date: isoDaysFromNow(-5), vehicleId: 'V003', regNumber: 'ET-OR-11296', reference: 'M004', vendor: null, unitPrice: 8000, notes: 'Front tyre replacement', balanceAfter: 8, performedBy: 'Priya Sharma' },
    { id: 'SL004', partId: 'SP002', partName: 'Oil Filter', type: 'Stock In', quantity: 20, date: isoDaysFromNow(-30), vehicleId: null, regNumber: null, reference: 'PO-2026-014', vendor: 'Moenco PLC', unitPrice: 350, notes: 'Quarterly restock', balanceAfter: 32, performedBy: 'Priya Sharma' },
  ];
  for (const l of spareLedger) {
    await prisma.spareLedgerEntry.upsert({ where: { id: l.id }, update: {}, create: l });
  }

  // --- Tyres ---
  const tyres = [
    { id: 'TY001', vehicleId: 'V001', regNumber: 'ET-AA-23715', serialNo: 'BS-SN-88231', brand: 'Bridgestone', model: 'R150', size: '12R22.5', type: 'Radial', position: 'Front Left', purchaseDate: isoDaysFromNow(-200), purchasePrice: 8000, vendor: 'Bridgestone Ethiopia', invoiceNo: 'INV-7781', warrantyType: 'Manufacturer', warrantyKm: 80000, warrantyExpiry: isoDaysFromNow(400), kmAtFitment: 100000, expectedLifeKm: 90000, currentKmRun: 84230, treadDepth: 6, lastPressureCheck: isoDaysFromNow(-5), lastRotationDate: isoDaysFromNow(-60), retreads: 0, status: 'In Use', notes: '' },
    { id: 'TY002', vehicleId: 'V003', regNumber: 'ET-OR-11296', serialNo: 'BS-SN-88245', brand: 'Bridgestone', model: 'R150', size: '12R22.5', type: 'Radial', position: 'Front Right', purchaseDate: isoDaysFromNow(-5), purchasePrice: 8000, vendor: 'Bridgestone Ethiopia', invoiceNo: 'INV-7912', warrantyType: 'Manufacturer', warrantyKm: 80000, warrantyExpiry: isoDaysFromNow(700), kmAtFitment: 98200, expectedLifeKm: 90000, currentKmRun: 0, treadDepth: 12, lastPressureCheck: isoDaysFromNow(-1), lastRotationDate: null, retreads: 0, status: 'In Use', notes: 'Newly fitted' },
    { id: 'TY003', vehicleId: 'V002', regNumber: 'ET-AA-44589', serialNo: 'GY-SN-44120', brand: 'Goodyear', model: 'G286', size: '11R22.5', type: 'Radial', position: 'Rear Left Outer', purchaseDate: isoDaysFromNow(-500), purchasePrice: 7200, vendor: 'Goodyear Ethiopia', invoiceNo: 'INV-6620', warrantyType: 'Manufacturer', warrantyKm: 70000, warrantyExpiry: isoDaysFromNow(-30), kmAtFitment: 200000, expectedLifeKm: 75000, currentKmRun: 56400, treadDepth: 3, lastPressureCheck: isoDaysFromNow(-10), lastRotationDate: isoDaysFromNow(-90), retreads: 1, status: 'Needs Replacement', notes: 'Tread wear near limit' },
    { id: 'TY004', vehicleId: 'V005', regNumber: 'ET-SD-33457', serialNo: 'TR-SN-22890', brand: 'Triangle', model: 'TR688', size: '10R20', type: 'Radial', position: 'Rear Right Inner', purchaseDate: isoDaysFromNow(-300), purchasePrice: 5400, vendor: 'Ethio Truck Service', invoiceNo: 'INV-5510', warrantyType: 'Dealer', warrantyKm: 60000, warrantyExpiry: isoDaysFromNow(180), kmAtFitment: 130000, expectedLifeKm: 65000, currentKmRun: 22800, treadDepth: 9, lastPressureCheck: isoDaysFromNow(-3), lastRotationDate: isoDaysFromNow(-45), retreads: 0, status: 'In Use', notes: '' },
    { id: 'TY005', vehicleId: 'V006', regNumber: 'ET-AA-99812', serialNo: 'SF-SN-11023', brand: 'Sunfull', model: 'HF768', size: '12R22.5', type: 'Radial', position: 'Front Left', purchaseDate: isoDaysFromNow(-40), purchasePrice: 6800, vendor: 'Sunfull East Africa', invoiceNo: 'INV-8990', warrantyType: 'Manufacturer', warrantyKm: 70000, warrantyExpiry: isoDaysFromNow(600), kmAtFitment: 41000, expectedLifeKm: 75000, currentKmRun: 200, treadDepth: 13, lastPressureCheck: isoDaysFromNow(-1), lastRotationDate: null, retreads: 0, status: 'In Use', notes: '' },
    { id: 'TY006', vehicleId: 'V008', regNumber: 'ET-AA-66047', serialNo: 'GY-SN-44877', brand: 'Goodyear', model: 'G286', size: '9R20', type: 'Radial', position: 'Rear Left Outer', purchaseDate: isoDaysFromNow(-600), purchasePrice: 6000, vendor: 'Goodyear Ethiopia', invoiceNo: 'INV-4002', warrantyType: 'Manufacturer', warrantyKm: 60000, warrantyExpiry: isoDaysFromNow(-90), kmAtFitment: 320000, expectedLifeKm: 60000, currentKmRun: 60100, treadDepth: 1, lastPressureCheck: isoDaysFromNow(-15), lastRotationDate: isoDaysFromNow(-120), retreads: 2, status: 'Needs Replacement', notes: 'Linked to current breakdown' },
  ];
  for (const t of tyres) {
    await prisma.tyre.upsert({ where: { id: t.id }, update: {}, create: t });
  }

  console.log('Demo data seeded: 6 users, 8 vehicles, 8 drivers, 8 trips, 8 fuel entries, 6 maintenance records, 8 compliance records, 4 consignments, 4 petty cash, 4 toll accounts, 5 toll transactions, 6 spare parts, 4 ledger entries, 6 tyres, payout pool.');
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
