-- CreateTable
CREATE TABLE "Consignment" (
    "id" TEXT NOT NULL,
    "cnNumber" TEXT NOT NULL,
    "cnDate" TEXT NOT NULL,
    "docType" TEXT NOT NULL,
    "against" TEXT NOT NULL,
    "againstNo" TEXT NOT NULL,
    "vehicleId" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "destination" TEXT NOT NULL,
    "consignor" TEXT NOT NULL,
    "consignorLocation" TEXT NOT NULL,
    "consignorGstin" TEXT NOT NULL,
    "consignee" TEXT NOT NULL,
    "consigneeLocation" TEXT NOT NULL,
    "consigneeGstin" TEXT NOT NULL,
    "billingParty" TEXT NOT NULL,
    "billingPartyLocation" TEXT NOT NULL,
    "billingPartyGstin" TEXT NOT NULL,
    "deliveryAt" TEXT NOT NULL,
    "loadType" TEXT NOT NULL,
    "paymentTerms" TEXT NOT NULL,
    "mode" TEXT NOT NULL,
    "godown" TEXT NOT NULL,
    "containerNo" TEXT NOT NULL,
    "sealNo" TEXT NOT NULL,
    "markNo" TEXT NOT NULL,
    "expectedDelivery" TEXT NOT NULL,
    "transporter" TEXT NOT NULL,
    "items" JSONB NOT NULL,
    "totalWeight" DOUBLE PRECISION NOT NULL,
    "totalFreight" INTEGER NOT NULL,
    "createdBy" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Consignment_pkey" PRIMARY KEY ("id")
);
