-- AlterTable: add the rest of the fields the frontend Tyre form actually uses
ALTER TABLE "Tyre"
ADD COLUMN "serialNo" TEXT NOT NULL DEFAULT '',
ADD COLUMN "model" TEXT NOT NULL DEFAULT '',
ADD COLUMN "size" TEXT NOT NULL DEFAULT '',
ADD COLUMN "type" TEXT NOT NULL DEFAULT '',
ADD COLUMN "position" TEXT NOT NULL DEFAULT '',
ADD COLUMN "purchaseDate" TEXT NOT NULL DEFAULT '',
ADD COLUMN "invoiceNo" TEXT NOT NULL DEFAULT '',
ADD COLUMN "warrantyType" TEXT NOT NULL DEFAULT '',
ADD COLUMN "kmAtFitment" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "treadDepth" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "lastPressureCheck" TEXT NOT NULL DEFAULT '',
ADD COLUMN "lastRotationDate" TEXT,
ADD COLUMN "notes" TEXT NOT NULL DEFAULT '',
ALTER COLUMN "warrantyKm" SET DEFAULT 0,
ALTER COLUMN "warrantyKm" SET NOT NULL;
